### ISSUE TITLE
Frameworks issues

### ISSUE THREAD

**Issue by KrishnaChandrapati** [XintianHan/ADV_ECG#1]
I am trying to implement using numpy 1.18, I am getting error. So, I deprecated NumPy version to 1.16, a bit of code is executed and throws an error. Can you please share all the environment details like pip list. So, it would be helpful for my minor thesis project.

**Comment by XintianHan** [comment]
What's the error you get?

**Comment by KrishnaChandrapati** [comment]
Thanks for the mail.
The error got fixed out,

With regards,
Krishna Sai Chandrapati,
+61-423338671
